### ISSUE TITLE
Write a player class

### ISSUE THREAD

**Issue by ericreads** [ericreads/WizardsAndWarlocks#6]
Write a basic player class with the ability to move up, down, left, and right with player input. Use a Rectangle class(import java.awt.*) to handle position and include a getter to return that rectangle. Include a private int to represent the health and add a takeDamage(int damage) method that subtracts from it. Include a boolean to represent if the player has died and have it be set to true when the health is <= 0. Use a placeholder rectangle for now instead of an actual sprite.

**Comment by thaneeshasiva** [comment]
I'll write the Player class! To be clear: the rectangle class (I'll call the instance 'position') represents the player's coordinates, to be used for collision detection later on?

**Comment by ericreads** [comment]
Yep, that sounds good.
